---
#title: "reporte1"
output: 
  pdf_document:
    includes:
      in_header: /Users/freddytapia/Documents/preambulo.tex
      #C:/Users/Freddy Tapia/Documents/preambulo.tex
      #/Users/dmorales/Documents/Vision/Riesgo-de-Mercado/app/preambulo.tex
      #paste(getwd(),"preambulo.tex",sep="/") 
      #~/Documents/Vision/liquidez/preambulo.tex
params:
  fecha: NA
  tabla_nominal: NA
  var_par_ind: NA
#   par_ns_t: NA
#   par_sven_t: NA
#   par_dl_t: NA
#   par_sp_t: NA
#   comp_pre_t: NA

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## VaR de Mercado

La fecha seleccionada para el cáculo del VaR es `r paste(substr(params$fecha,9,10),substr(params$fecha,6,7),substr(params$fecha,1,4),sep = "/")`

```{r,echo = FALSE}
library(knitr)
#kable(paste(substr(params$fecha,9,10),substr(params$fecha,6,7),substr(params$fecha,1,4),sep = "/"),align="c")
```

## Valor Nominal

```{r,echo = FALSE}
#library(kableExtra)
library(knitr)
#library(magrittr)
options(scipen=999)
kable(data.frame(params$tabla_nominal[,1],prettyNum(params$tabla_nominal[,2], scientific=FALSE, big.mark=".")),col.names=c("Títulos","Valor Nominal"),align=c("c","r")) 
#%>%
 # kable_styling(c("striped", "bordered")) 

#grafico
posicion_tif <- cbind.data.frame(params$tabla_nominal[,1],params$tabla_nominal[,2])
    names(posicion_tif) <- c("titulo","valor_nominal")
    
posicion_tif  %>%
  arrange(valor_nominal) %>%
  mutate(Titulo=factor(titulo, titulo)) %>%
  ggplot( aes(x=Titulo, y=valor_nominal) ) +
  geom_segment( aes(x=Titulo ,xend=Titulo, y=0, yend=valor_nominal), color="grey") +
  geom_point(size=3, color="#69b3a2") +
  coord_flip() +
  theme(
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.position="none"
  ) +
  xlab("")
    
# p <- ggplot(posicion_tif, aes(titulo, valor_nominal, fill = titulo)) + 
#   geom_bar(position="stack", stat="identity",show.legend = FALSE) + coord_flip() + 
#   labs(x = "Títulos",y = "Valor Nominal")+
#   theme(axis.text.y=element_text(angle=0, hjust=1))
# print(p) 

```

Opción 2

```{r,echo = FALSE}
#library(kableExtra)
library(knitr)
#library(magrittr)
options(scipen=999)

#grafico
posicion_tif <- cbind.data.frame(params$tabla_nominal[,1],params$tabla_nominal[,2])
    names(posicion_tif) <- c("titulo","valor_nominal")
    

p <- ggplot(posicion_tif, aes(reorder(titulo,valor_nominal), valor_nominal, fill = titulo)) + 
  geom_bar(position="stack", stat="identity",show.legend = FALSE) + coord_flip() + 
  labs(x = "Títulos",y = "Valor Nominal")+
  theme(axis.text.y=element_text(angle=0, hjust=1))
print(p) 

```


##VaR Paramétrico

Vares individuales

```{r,echo = FALSE}
library(knitr)
var <- cbind.data.frame(rownames(params$var_par_ind),params$var_par_ind[,1],prettyNum(params$var_par_ind[,3], scientific=FALSE, big.mark="."),params$var_par_ind[,4])
names(var) <- c("Título","Desviación Estandar","VaR Individual","Porcentaje VaR")
kable(var,align="c")
```

Gráfico

```{r,echo = FALSE}
library(knitr)
options(scipen=999)

#grafico
var <- cbind.data.frame(rownames(params$var_par_ind),params$var_par_ind[,1],params$var_par_ind[,3],params$var_par_ind[,4])
var <- var[-nrow(var),]
names(var) <- c("titulo","sd","var_ind","por_var")

p <- ggplot(var, aes(reorder(titulo,var_ind), var_ind, fill = titulo)) + 
  geom_bar(position="stack", stat="identity",show.legend = FALSE) + coord_flip() + 
  labs(x = "Títulos",y = "VaRes Individuales")+
  theme(axis.text.y=element_text(angle=0, hjust=1))
print(p) 

```

##VaR por Simulación Histórica

##VaR por Simulación de Montecarlo





